SistemaInventario/Areas/Admin/Controllers/BodegaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SistemaInventario.AccesoDatos.Repositorio.IRepositorio;
using SistemaInventario.Modelos;

namespace SistemaInventario.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BodegaController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;

        public BodegaController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo = unidadTrabajo;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            Bodega bodega = new Bodega();
            if (id == null)
            {
                // Esto es para Crear nuevo Registro
                return View(bodega);
            }
            // Esto es para Actualizar
            bodega = _unidadTrabajo.Bodega.Obtener(id.GetValueOrDefault());
            if (bodega == null)
            {
                return NotFound();
            }

            return View(bodega);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Bodega bodega)
        {
            if (ModelState.IsValid)
            {
                if (bodega.Id == 0)
                {
                    _unidadTrabajo.Bodega.Agregar(bodega);
                }
                else
                {
                    _unidadTrabajo.Bodega.Actualizar(bodega);
                }
                _unidadTrabajo.Guardar();
                return RedirectToAction(nameof(Index));
            }
            return View(bodega);
        }




        #region API
        [HttpGet]
        public IActionResult ObtenerTodos()
        {
            var todos = _unidadTrabajo.Bodega.ObtenerTodos();
            return Json(new { data = todos });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var bodegaDb = _unidadTrabajo.Bodega.Obtener(id);
            if(bodegaDb == null)
            {
                return Json(new { success = false, message = "Error al Borrar" });
            }
            _unidadTrabajo.Bodega.Remover(bodegaDb);
            _unidadTrabajo.Guardar();
            return Json(new { success = true, message = "Bodega Borrada Exitosamente" });
        }

        #endregion
    }
}

SistemaInventario/Areas/Inventario/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SistemaInventario.Modelos.ViewModels;


namespace SistemaInventario.Areas.Inventario.Controllers
{
    [Area("Inventario")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaInventario/Areas/Admin/Views/Bodega/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />

<div class="row">
    <div class="col-6">
        <h2 class="text-primary"> Lista de Bodegas </h2>
    </div>
    <div class="col-6 text-right">
        <a class="btn btn-primary" asp-action="Upsert"> <i class="fas fa-plus"></i> Crear Nueva Bodega </a>
    </div>
</div>

<br />

<div class="p-4 border rounded">
    <table id="tblDatos" class="table table-striped table-bordered" style="width:100%">
        <thead class="thead-dark">
            <tr class="table-info">
                <th>Nombre</th>
                <th>Descripcion</th>
                <th>Estado</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>



@section Scripts{
    <script src="~/js/bodega.js"></script>
}

SistemaInventario/Areas/Admin/Views/Bodega/Upsert.cshtml
@model SistemaInventario.Modelos.Bodega

@{
   
    Layout = "~/Views/Shared/_Layout.cshtml";
    var titulo = "Crear Bodega";
}

<form method="post">
    <div class="row p-3 border-0">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
    @if (Model.Id!=0)
    {
        // Actualizar
        titulo = "Actualizar Bodega";
    }

    <div class="col-12 border-bottom">
        <h2 class="text-primary">@titulo</h2>
    </div>
    <div class="col-8 pt-4">
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Nombre"></label>
            </div>
            <div class="col-8">
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Descripcion"></label>
            </div>
            <div class="col-8">
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Estado"></label>
            </div>
            <div class="col-4">
                <select asp-for="Estado" class="form-control">
                    <option value=true>Activo</option>
                    <option value=false>Inactivo</option>
                </select>
            </div>
        </div>
        
        <div class="form-group row">
            <div class="col-8 offset-4">
                @if (Model.Id!=0)
                {
                    <partial name="_BotonesActualizarYRegresar" model="Model.Id"/>
                }
                else
                {
                    <partial name="_BotonesCrearYRegresar"/>
                }
            </div>
        </div>

    </div>

</form>

@section Scripts {
 <partial name="_ValidationScriptsPartial"/>
}

SistemaInventario/Areas/Inventario/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenidos a mi Aplicacion</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SistemaInventario/Views/Shared/_BotonesActualizarYRegresar.cshtml
@model int

    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Actualizar</button>
        </div>
        <div class="col">
            <a asp-action="Index" class="btn btn-success form-control">Regresar</a>
        </div>
    </div>

SistemaInventario/Views/Shared/_BotonesCrearYRegresar.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Crear</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Regresar</a>
    </div>
</div>

SistemaInventario/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaInventario</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SistemaInventario</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Contenido
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Bodega" asp-action="Index">Bodega</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary text-white-50">
        <div class="container">
            &copy; 2020 - SistemaInventario
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>